### ISSUE TITLE
Button/modifier key to quickly unselect all but one engines

### ISSUE THREAD

**Issue by linusg** [test262-fyi/test262.fyi#15]
A common use case is seeing what the results of one specific engine are, which currently requires manually unselecting all other engines. There should either be a button to unselect all, or something like Alt+click unselecting all but the clicked checkbox.

**Comment by CanadaHonk** [comment]
You can unselect all easier now with groups and the heading checkboxes, but I like the idea of alt+click too.

**Comment by linusg** [comment]
Current solution seems fine :)
