### ISSUE TITLE
v8_exp,3 failing with exit code 143, likely OOM

### ISSUE THREAD

**Issue by nektro** [test262-fyi/test262.fyi#37]
https://test262.fyi/#|v8_exp

**Comment by CanadaHonk** [comment]
Thanks for filing, I was meaning to look into but have been busy for a bit. If OOM on the harness side, a bit weird it happens only with this and also that it happens at all considering we already use `NODE_OPTIONS="--max-old-space-size=4096"`.

**Comment by nektro** [comment]
last line of log at time of writing
`PASS 13875 test/built-ins/Temporal/PlainDate/prototype/until/roundingincrement-wrong-type.js`
`Error: Process completed with exit code 143.`

next one is
`13876 test/built-ins/Temporal/PlainDate/prototype/until/roundingincrement-wrong-type.js`

**Comment by nektro** [comment]
hmm I thought maybe SIGTERM could also be crash but it seems to fail at different locations

`PASS 13842`
`PASS 13715`
`FAIL 13725`
`PASS 13202`
...

**Comment by linusg** [comment]
Options were updated in https://github.com/CanadaHonk/eshost/commit/b8a4108ed55e37b98a8d045943e50e19428712ca, works fine on new runner host
