### ISSUE TITLE
Babel tests

### ISSUE THREAD

**Issue by nicolo-ribaudo** [test262-fyi/test262.fyi#4]
We run test262 on Babel and core-js regularly, and it would be very nice to show the results on https://test262.fyi.

> I just noticed that our test262 runner on CI is completely broken and it's not reporting results, but for the purpose of this issue let's assume that it works, while I fix it 😅  

We run test262 on every commit, and  store the result in a `test262-result` artifact -- you can find the last one https://github.com/babel/babel/actions/runs/5179541745.

We run tests by compiling them to ES5 using Babel, injecting the core-js polyfill, and running the resulting code in a very old version of Node.js (0.10) which only supported ES5. This means that our test results aren't significant for pre-ES6 behavior, but they are useful for features introduced since then.

We use https://github.com/babel/babel-test262-runner/ to run them, which produces tap output. The readme doesn't mention it, but it's possible to specify the path to a different test262 checkout using the `TEST262_PATH=....` env variable.

**Comment by nicolo-ribaudo** [comment]
Something is still broken, many more tests than expected are failing.

**Comment by CanadaHonk** [comment]
After a lot of tinkering, Babel builds should now be generated with the same harness (after some updates) while using Babel's test262 transpile script.

**Comment by CanadaHonk** [comment]
Results are on site! Not perfect/very accurate results but works :)
![image](https://github.com/CanadaHonk/test262.fyi/assets/19228318/95cf31fb-a7d2-4b10-bdf0-59a3fd5be293)

**Comment by nicolo-ribaudo** [comment]
Oh awesome :) Let's keep this issue open for a while, so I can check if there is anything that can be improved for the Babel runner and I'll post comments here.

**Comment by linusg** [comment]
This seems to be working as intended :)
