### ISSUE TITLE
Outdated stages for specs

### ISSUE THREAD

**Issue by nektro** [test262-fyi/test262.fyi#43]
https://github.com/tc39/proposal-resizablearraybuffer

**Comment by CanadaHonk** [comment]
We read stages from the repos so they should be up to date, merging issues into one.

**Comment by nektro** [comment]
ah gotcha, yeah it seems they changed the readme to say stage 4 but `spec.html` is still 3 which is what the website reflects

**Comment by linusg** [comment]
@nektro are there any with outdated info left after your various updates?

**Comment by nektro** [comment]
nope should be good now

**Comment by nektro** [comment]
also the visual issue this was pointing out was actually fixed by https://github.com/tc39/test262/pull/4132 and https://github.com/tc39/test262/pull/4150
