### ISSUE TITLE
Chakra is broken

### ISSUE THREAD

**Issue by linusg** [test262-fyi/test262.fyi#65]
...and I don't think at this point it's worth fixing.

```
📦 jsvu v2.1.0 — the JavaScript engine Version Updater 📦
✔ Read OS from config: linux64
✔ Read engines from config: chakra
❯ Finding the latest Chakra version…
✖ RequestError: getaddrinfo ENOTFOUND chakratestx.file.core.windows.net
```

**Comment by CanadaHonk** [comment]
Fixed probably in https://github.com/CanadaHonk/jsvu/commit/7ce8e8474328f7716a5852c90922edf058ff1efd + https://github.com/CanadaHonk/jsvu/commit/be2ccb8d8516c645dd9f9b547fb0d1ec2f0969e9
