### ISSUE TITLE
add NJS support

### ISSUE THREAD

**Issue by michaelficarra** [test262-fyi/test262.fyi#71]
See https://github.com/nginx/njs

NJS is a complete JavaScript engine developed to be embedded in nginx as a dynamic nginx module. NJS can be run outside of nginx using the CLI or the REPL: https://nginx.org/en/docs/njs/cli.html. It would be nice to be able to see how it compares to other popular engines on spec compliance. If you need help, I should be able to connect you with the NJS devs, so just let me know.

**Comment by CanadaHonk** [comment]
TIL it uses its own engine (mostly?), definitely interested in adding it!

**Comment by linusg** [comment]
Do they have or are willing to add the functions required for an eshost-compatible runtime? (https://github.com/CanadaHonk/eshost/tree/master/runtimes)

**Comment by michaelficarra** [comment]
> TIL it uses its own engine (mostly?), definitely interested in adding it!

Yep, completely from scratch as far as I'm aware.

> Do they have or are willing to add the functions required for an eshost-compatible runtime?

I'll ask!

**Comment by linusg** [comment]
I added basic NJS support to our eshost fork in https://github.com/CanadaHonk/eshost/pull/17, the stubbed methods are what would be needed on their end for a complete runtime. This is not blocking, it just means that certain tests won't run.

**Comment by linusg** [comment]
Draft PR for NJS test262.fyi integration: https://github.com/test262-fyi/test262.fyi/pull/72

**Comment by linusg** [comment]
@michaelficarra results are in: https://test262.fyi/#%7Cnjs
