### ISSUE TITLE
JSC Always shows when all engines are untoggled

### ISSUE THREAD

**Issue by eliassjogreen** [test262-fyi/test262.fyi#74]
There is an issue currently where JSC experimental always shows when you untoggle all engines.

https://test262.fyi/#|

![Image of JSC showing](https://github.com/user-attachments/assets/0bed92ad-805d-4a72-b990-4b51a53fce1c)

**Comment by CanadaHonk** [comment]
Already fixed, should work fine in next run (~tomorrow)
